name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      code_signing:
        description: "コード署名するかどうか"
        default: ""

env:
  # コード署名するかどうか
  CODE_SIGNING: ${{ github.event.inputs.code_signing }}

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: ${{ env.CODE_SIGNING != '' && 'hoge' || '' }}
    steps:
      - uses: actions/checkout@master

      - if: ${{ env.CODE_SIGNING != '' }}
        shell: bash
        run: bash codesign.bash
        env:
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: run.exe
          path: run.exe
