name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      CODE_SIGNING:
        description: "コード署名するかどうか"
        default: ""

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.CODE_SIGNING != '' && 'hoge' || '' }}
    steps:
      - uses: actions/checkout@master

      - shell: bash
        run: bash codesign.bash
        env:
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: run.exe
          path: run.exe
