name: Build

on:
  push:
    branches:
      - main

env:
  DEBUG: "1"

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: ${{ env.DEBUG != '' && 'hoge' || '' }}
    steps:
      # - uses: actions/checkout@master

      - shell: bash
        run: |
          echo ok
          echo secret "$HOGEENV"
        env:
          HOGEENV: ${{ secrets.HOGEENV }}
