name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      DEBUG:
        default: "1"

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.DEBUG != '' && '' || 'fuga' }}
    steps:
      # - uses: actions/checkout@master

      - shell: bash
        run: |
          echo ok
          echo debug "${{ github.event.inputs.DEBUG }}"
          echo secret "$HOGEENV"
        env:
          HOGEENV: ${{ secrets.HOGEENV }}
