name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      DEBUG:
        default: "1"

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: 'hoge'
    # environment: ${{ github.event.inputs.DEBUG != '' && '' || 'hoge' }}
    steps:
      - uses: actions/checkout@master

      - shell: bash
        run: bash codesign.bash
        env:
          CERT_BASE64: ${{ secrets.CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: run.exe
          path: run.exe
