name: Build

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     code_signing:
  #       description: "コード署名する"
  #       type: boolean

# jobs:
#   hoge-job:
#     runs-on: windows-latest
#     environment: hoge
#     steps:
#       - uses: actions/checkout@master

#       # - if: github.event.inputs.code_signing
#       - shell: bash
#         run: bash codesign.bash "run.exe"
#         env:
#           ESIGNERCKA_USERNAME: ${{ secrets.ESIGNERCKA_USERNAME }}
#           ESIGNERCKA_PASSWORD: ${{ secrets.ESIGNERCKA_PASSWORD }}
#           ESIGNERCKA_TOTP_SECRET: ${{ secrets.ESIGNERCKA_TOTP_SECRET }}

#       # - if: github.event.inputs.code_signing
#       - shell: bash
#         run: bash codesign.bash "*.dll"
#         env:
#           ESIGNERCKA_USERNAME: ${{ secrets.ESIGNERCKA_USERNAME }}
#           ESIGNERCKA_PASSWORD: ${{ secrets.ESIGNERCKA_PASSWORD }}
#           ESIGNERCKA_TOTP_SECRET: ${{ secrets.ESIGNERCKA_TOTP_SECRET }}

#       - uses: actions/upload-artifact@master
#         with:
#           name: run.exe
#           path: run.exe

jobs:
  hoge-job:
    runs-on: windows-latest
    environment: hoge
    defaults:
      run:
        working-directory: ./new-electron-webpack-project
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # 空打ち
      - shell: bash
        run: bash ../codesign.bash "dummydummydummy.exe"
        env:
          ESIGNERCKA_USERNAME: ${{ secrets.ESIGNERCKA_USERNAME }}
          ESIGNERCKA_PASSWORD: ${{ secrets.ESIGNERCKA_PASSWORD }}
          ESIGNERCKA_TOTP_SECRET: ${{ secrets.ESIGNERCKA_TOTP_SECRET }}

      - name: build
        run: |
          THUMBPRINT=$(
              powershell '
                  $CodeSigningCert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
                  echo "$($CodeSigningCert.Thumbprint)"
              '
          )
          echo "THUMBPRINT: $THUMBPRINT"

          # electron-builder.config.js の `const certificateSha1 = null;`を置き換える
          sed -i "s/const certificateSha1 = null;/const certificateSha1 = '$THUMBPRINT';/g" ./electron-builder.config.js

          yarn
          yarn dist

      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
